### ISSUE TITLE
Starbase Tiles are Vanilla

### ISSUE THREAD

**Issue by helloitisjoshua** [lyratcm/mergelite#15]
<img width="400" alt="Screen Shot 2022-08-27 at 7 54 36 PM" src="https://user-images.githubusercontent.com/64818186/187055428-4caa49a4-cffc-4e40-86a5-50fa68d939b4.png">
Starbase tiles have been reduced.

**Comment by lyratcm** [comment]
Fixed, tweaked that values a bit now that starbasess are stronger
